#!/bin/bash
# SemOps2 Generated File Validator
# Checks if generated files are modified and enforces generation rules

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Generated file patterns to protect
GENERATED_PATTERNS=(
    "src/semops/generated/**/*.py"
    "src/semops/generated/**/*.pyi"
    "generated/docs/**/*"
    "generated/api/**/*"
    "*.pb2.py"
    "*_pb2.py"
    "*.pb2_grpc.py"
    "*_pb2_grpc.py"
    "*.swagger.json"
    "*.swagger.yaml"
)

# Schema files that when changed require regeneration
SCHEMA_PATTERNS=(
    "schema/**/*.proto"
    "buf.yaml"
    "buf.gen.yaml"
)

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if file matches any pattern
matches_pattern() {
    local file="$1"
    shift
    local patterns=("$@")

    for pattern in "${patterns[@]}"; do
        if [[ "$file" == $pattern ]]; then
            return 0
        fi
    done
    return 1
}

# Get list of staged files
get_staged_files() {
    git diff --cached --name-only --diff-filter=ACMR
}

# Get list of modified files (including unstaged)
get_modified_files() {
    git diff --name-only --diff-filter=ACMR HEAD
}

# Check if any schema files are modified
check_schema_changes() {
    local files=("$@")
    local schema_changed=false

    for file in "${files[@]}"; do
        if matches_pattern "$file" "${SCHEMA_PATTERNS[@]}"; then
            log_info "Schema file changed: $file"
            schema_changed=true
        fi
    done

    echo $schema_changed
}

# Check for manual modifications to generated files
check_generated_file_modifications() {
    local files=("$@")
    local violations=()

    log_info "Checking for manual modifications to generated files..."

    for file in "${files[@]}"; do
        if matches_pattern "$file" "${GENERATED_PATTERNS[@]}"; then
            # Check if this is a deletion (allowed for regeneration)
            if [[ ! -f "$PROJECT_ROOT/$file" ]]; then
                log_info "  ✓ Deletion allowed: $file"
                continue
            fi

            # Check if file has the generated file marker
            if [[ "$file" == *.py ]]; then
                if head -n 10 "$PROJECT_ROOT/$file" | grep -q "Generated by.*DO NOT EDIT\|# Generated\|@generated\|Code generated by"; then
                    log_warning "  ✗ Generated file modified: $file"
                    violations+=("$file")
                else
                    # Check common protobuf generated patterns
                    if [[ "$file" == *_pb2.py ]] || [[ "$file" == *_pb2_grpc.py ]]; then
                        log_warning "  ✗ Protobuf generated file modified: $file"
                        violations+=("$file")
                    fi
                fi
            elif [[ "$file" == *.json ]] || [[ "$file" == *.yaml ]] || [[ "$file" == *.html ]] || [[ "$file" == *.md ]]; then
                # These are typically generated documentation/API files
                if [[ "$file" == generated/* ]] || [[ "$file" == *swagger* ]] || [[ "$file" == *openapi* ]]; then
                    log_warning "  ✗ Generated documentation/API file modified: $file"
                    violations+=("$file")
                fi
            fi
        fi
    done

    if [[ ${#violations[@]} -gt 0 ]]; then
        return 1
    fi
    return 0
}

# Validate that generated files are in sync with schemas
validate_generated_sync() {
    log_info "Validating generated files are in sync with schemas..."

    cd "$PROJECT_ROOT"

    # Check if we can generate without errors
    if ! buf lint >/dev/null 2>&1; then
        log_error "Schema validation failed - cannot validate generated files"
        return 1
    fi

    # Create temporary directory for fresh generation
    local temp_dir=$(mktemp -d)
    local temp_generated="$temp_dir/generated"

    trap "rm -rf '$temp_dir'" EXIT

    # Generate to temporary location
    mkdir -p "$temp_generated"

    # Create temporary buf.gen.yaml pointing to temp directory
    local temp_gen_config="$temp_dir/buf.gen.yaml"
    sed "s|src/semops/generated|$temp_generated|g" "$PROJECT_ROOT/buf.gen.yaml" > "$temp_gen_config"

    log_info "  - Generating fresh code for comparison..."
    if ! buf generate --config "$temp_gen_config" >/dev/null 2>&1; then
        log_error "Code generation failed"
        return 1
    fi

    # Compare with existing generated files
    local current_generated="$PROJECT_ROOT/src/semops/generated"
    if [[ -d "$current_generated" ]]; then
        if ! diff -r "$current_generated" "$temp_generated" >/dev/null 2>&1; then
            log_warning "Generated files are out of sync with schemas"
            log_warning "Differences found between current and fresh generation"
            return 1
        fi
    fi

    log_success "Generated files are in sync with schemas"
    return 0
}

# Regenerate files if needed
regenerate_files() {
    log_info "Regenerating files..."

    cd "$PROJECT_ROOT"

    # Update dependencies first
    log_info "  - Updating buf dependencies..."
    if ! buf dep update; then
        log_error "Failed to update buf dependencies"
        return 1
    fi

    # Generate code
    log_info "  - Generating protobuf code..."
    if ! buf generate; then
        log_error "Code generation failed"
        return 1
    fi

    log_success "Files regenerated successfully"
    return 0
}

# Main validation function
validate_commit() {
    local staged_files
    staged_files=($(get_staged_files))

    if [[ ${#staged_files[@]} -eq 0 ]]; then
        log_info "No staged files to validate"
        return 0
    fi

    log_info "Validating ${#staged_files[@]} staged files..."

    # Check for manual modifications to generated files
    if ! check_generated_file_modifications "${staged_files[@]}"; then
        log_error ""
        log_error "❌ COMMIT BLOCKED: Manual changes detected to generated files"
        log_error ""
        log_error "Generated files should not be manually edited. Instead:"
        log_error "  1. Modify the source schemas in schema/**/*.proto"
        log_error "  2. Update buf.gen.yaml if needed"
        log_error "  3. Run 'buf generate' to regenerate code"
        log_error "  4. Commit both schema changes and regenerated files"
        log_error ""
        log_error "If you need to bypass this check (emergency only):"
        log_error "  git commit --no-verify"
        log_error ""
        return 1
    fi

    # Check if schema files were changed
    local schema_changed
    schema_changed=$(check_schema_changes "${staged_files[@]}")

    if [[ "$schema_changed" == "true" ]]; then
        log_info "Schema changes detected, validating generated files..."
        if ! validate_generated_sync; then
            log_warning ""
            log_warning "⚠️  Schema changes detected but generated files may be out of sync"
            log_warning ""
            log_warning "Please regenerate files:"
            log_warning "  buf generate"
            log_warning ""
            log_warning "Then stage the regenerated files:"
            log_warning "  git add src/semops/generated/ generated/"
            log_warning ""
            return 1
        fi
    fi

    log_success "All generated file validations passed"
    return 0
}

# Show help
show_help() {
    echo "SemOps2 Generated File Validator"
    echo ""
    echo "Usage: $0 [command] [options]"
    echo ""
    echo "Commands:"
    echo "  validate    - Validate staged files (default)"
    echo "  check       - Check all files for sync issues"
    echo "  regenerate  - Regenerate all generated files"
    echo "  help        - Show this help"
    echo ""
    echo "Options:"
    echo "  --fix       - Automatically fix issues when possible"
    echo "  --verbose   - Enable verbose output"
    echo ""
    echo "Examples:"
    echo "  $0                    # Validate staged files"
    echo "  $0 check              # Check all files"
    echo "  $0 regenerate         # Regenerate files"
    echo "  $0 validate --fix     # Validate and fix issues"
}

# Parse command line arguments
COMMAND="${1:-validate}"
FIX_ISSUES=false
VERBOSE=false

shift || true

while [[ $# -gt 0 ]]; do
    case $1 in
        --fix)
            FIX_ISSUES=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Execute command
case "$COMMAND" in
    "validate")
        validate_commit
        ;;
    "check")
        modified_files=($(get_modified_files))
        if [[ ${#modified_files[@]} -gt 0 ]]; then
            check_generated_file_modifications "${modified_files[@]}"
        else
            log_info "No modified files to check"
        fi
        ;;
    "regenerate")
        regenerate_files
        ;;
    "help"|"--help"|"-h")
        show_help
        exit 0
        ;;
    *)
        log_error "Unknown command: $COMMAND"
        show_help
        exit 1
        ;;
esac